[package]
name = "oa42-macros"
version = "0.1.0"
edition = "2021"
description = "Macros for oa42"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.OpenApi42.org"
repository = "git@github.com:LuvDaSun/OpenApi42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.82"
quote = "^1.0.35"
syn = "2.0.64"


[lib]
proc-macro = true
