[package]
name = "oa42-core"
version = "0.1.0"
edition = "2021"
description = "Core of oa42"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.OpenApi42.org"
keywords = ["openapi", "api"]
repository = "git@github.com:LuvDaSun/OpenApi42"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "^1.0.158", features = ["derive"] }
serde_json = "^1.0.94"
quote = "^1.0.35"
futures = { version = "0.3.30" }
serde_yaml = "^0.9.31"
once_cell = "^1.19.0"
regex = "^1.10.3"
urlencoding = "2.1.3"
semver = "1.0.23"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
jns42-core = "0.1.0"
oa42-macros = { path = "../oa42-macros" }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
surf = "2.3.2"


[lib]
crate-type = ["rlib", "cdylib"]
